"""Application services that coordinate ports and transactional adapters."""

from enterprise_rag.services.answer_verification import (
    AnswerDraft,
    AnswerOutcome,
    AnswerStatus,
    AnswerVerificationService,
    DraftCitation,
    DraftParagraph,
    RepairRequest,
    VerificationIssue,
)
from enterprise_rag.services.auth import AnonymousSessionService, Principal, SessionGrant
from enterprise_rag.services.cost_guard import (
    BoundedLanguageModel,
    BudgetedQueryRunner,
    CostGuard,
    QueryBudget,
)
from enterprise_rag.services.deep_recovery import (
    DeepRecoveryController,
    DeepRecoveryOutcome,
    DeepRecoveryRequest,
    EvidenceAssessment,
    EvidenceDecision,
    EvidenceItem,
    EvidenceLedger,
    RecoveryAction,
    RecoveryPlanner,
    RecoveryRoute,
    RetrievalMode,
)
from enterprise_rag.services.documents import DocumentRegistrationService, RegisterDocument
from enterprise_rag.services.eval_runner import (
    EvaluationBudgetExceeded,
    EvaluationRunner,
    GoldenFixtureSubject,
    MemoryEvaluationResultCache,
    evaluation_report_dict,
    write_evaluation_report,
)
from enterprise_rag.services.evaluation import DeterministicEvaluator
from enterprise_rag.services.evaluation_workspace import (
    EvaluationCatalog,
    EvaluationComparison,
    EvaluationProfile,
    EvaluationWorkspaceService,
)
from enterprise_rag.services.fusion import FusionDiagnostic, FusionResult, ReciprocalRankFusion
from enterprise_rag.services.golden_set import GoldenSetLoader, GoldenSetValidationError
from enterprise_rag.services.health import (
    ComponentHealth,
    ConfigurationHealthProbe,
    HealthProbe,
    HealthReport,
    HealthService,
    HealthStatus,
    PostgreSQLHealthProbe,
)
from enterprise_rag.services.images import EnrichedImage, ImageEnricher, ImageEnrichmentResult
from enterprise_rag.services.ingestion import IngestionPipeline, PipelineRunResult
from enterprise_rag.services.ingestion_trace import (
    IngestionTraceBatch,
    IngestionTraceStage,
    IngestionTraceView,
    project_ingestion_trace,
)
from enterprise_rag.services.knowledge import (
    KnowledgeApplication,
    KnowledgeQuery,
    McpApplicationService,
)
from enterprise_rag.services.language_model_reasoning import (
    AuthoredAnswer,
    LanguageModelAnswerAuthor,
    LanguageModelEvidenceAssessor,
    ModelUsage,
)
from enterprise_rag.services.lifecycle import (
    DeletionResult,
    DeletionStep,
    DocumentDeletionService,
    ReconcileIssue,
    ReconcileIssueKind,
    ReconcileReport,
    ReconcileService,
)
from enterprise_rag.services.llm_judge import (
    JudgeResponseError,
    LanguageModelJudge,
    configure_optional_llm_judge,
)
from enterprise_rag.services.local_query import DeterministicLocalQueryRunner
from enterprise_rag.services.manual_llm_cleaning import (
    LlmCleaningPreflight,
    LlmCleaningResult,
    ManualLlmCleaningService,
)
from enterprise_rag.services.overview import (
    OverviewActivity,
    WorkspaceOverview,
    WorkspaceOverviewService,
)
from enterprise_rag.services.projection import (
    ProjectionError,
    ProjectionRequest,
    ProjectionResult,
    ProjectionService,
)
from enterprise_rag.services.provider_reindex import (
    ProviderIndexDocument,
    ProviderIndexStatus,
    ProviderReindexItem,
    ProviderReindexResult,
    ProviderReindexService,
)
from enterprise_rag.services.quality_gate import (
    QualityGatePolicy,
    QualityGatePolicyError,
    QualityGateResult,
    SparseGoldenSubject,
    evaluate_quality_gate,
    load_quality_gate_policy,
)
from enterprise_rag.services.query_api import (
    QueryApiService,
    QueryCommand,
    QueryExecution,
    QueryProgress,
    QueryProgressStage,
    QueryRunStatus,
    QueryStreamEvent,
)
from enterprise_rag.services.query_planner import PlannerOutcome, QueryPlanningService
from enterprise_rag.services.query_trace import (
    QueryDegradation,
    QueryRankChange,
    QueryRecoveryRound,
    QueryTraceView,
    QueryWaterfallStage,
    project_query_trace,
)
from enterprise_rag.services.reranking import RerankingService, RerankItem, RerankOutcome
from enterprise_rag.services.retrieval import (
    DualSearchResult,
    DualSearchService,
    SearchBranchResult,
    SearchDiagnostic,
    SearchMethod,
)
from enterprise_rag.services.scope_root import (
    PreparedRerankCandidates,
    RecoveredContext,
    RootContext,
    ScopeRootService,
)
from enterprise_rag.services.semantic_query import SemanticQueryRunner
from enterprise_rag.services.standard_graph import (
    QueryGraphStage,
    QueryGraphStatus,
    StageTransition,
    StandardQueryGraph,
    StandardQueryRequest,
    StandardQueryResult,
)
from enterprise_rag.services.traces import TraceService, build_persistent_tracing
from enterprise_rag.services.worker import IngestionWorker
from enterprise_rag.services.workspace import (
    DocumentImage,
    JobListItem,
    JobPage,
    WorkspaceService,
)

__all__ = [
    "AnswerDraft",
    "AnswerOutcome",
    "AnswerStatus",
    "AnswerVerificationService",
    "BoundedLanguageModel",
    "BudgetedQueryRunner",
    "CostGuard",
    "DeletionResult",
    "DeletionStep",
    "DocumentDeletionService",
    "DocumentImage",
    "DocumentRegistrationService",
    "EvaluationBudgetExceeded",
    "EvaluationCatalog",
    "EvaluationComparison",
    "EvaluationProfile",
    "EvaluationRunner",
    "EvaluationWorkspaceService",
    "GoldenSetLoader",
    "GoldenSetValidationError",
    "GoldenFixtureSubject",
    "DeterministicEvaluator",
    "DeterministicLocalQueryRunner",
    "DeepRecoveryController",
    "DeepRecoveryOutcome",
    "DeepRecoveryRequest",
    "DualSearchResult",
    "DualSearchService",
    "DraftCitation",
    "DraftParagraph",
    "EnrichedImage",
    "EvidenceAssessment",
    "EvidenceDecision",
    "EvidenceItem",
    "EvidenceLedger",
    "FusionDiagnostic",
    "FusionResult",
    "ImageEnricher",
    "ImageEnrichmentResult",
    "AuthoredAnswer",
    "LanguageModelAnswerAuthor",
    "LanguageModelEvidenceAssessor",
    "ModelUsage",
    "ComponentHealth",
    "ConfigurationHealthProbe",
    "HealthProbe",
    "HealthReport",
    "HealthService",
    "HealthStatus",
    "IngestionPipeline",
    "IngestionWorker",
    "IngestionTraceBatch",
    "IngestionTraceStage",
    "IngestionTraceView",
    "KnowledgeApplication",
    "KnowledgeQuery",
    "LlmCleaningPreflight",
    "LlmCleaningResult",
    "JudgeResponseError",
    "JobListItem",
    "JobPage",
    "LanguageModelJudge",
    "AnonymousSessionService",
    "PipelineRunResult",
    "PlannerOutcome",
    "McpApplicationService",
    "MemoryEvaluationResultCache",
    "ManualLlmCleaningService",
    "OverviewActivity",
    "Principal",
    "ProjectionError",
    "ProjectionRequest",
    "ProjectionResult",
    "ProjectionService",
    "ProviderIndexDocument",
    "ProviderIndexStatus",
    "ProviderReindexItem",
    "ProviderReindexResult",
    "ProviderReindexService",
    "QualityGatePolicy",
    "QualityGatePolicyError",
    "QualityGateResult",
    "PostgreSQLHealthProbe",
    "QueryPlanningService",
    "QueryGraphStage",
    "QueryGraphStatus",
    "QueryDegradation",
    "QueryRankChange",
    "QueryRecoveryRound",
    "QueryTraceView",
    "QueryWaterfallStage",
    "QueryApiService",
    "QueryBudget",
    "QueryCommand",
    "QueryExecution",
    "QueryProgress",
    "QueryProgressStage",
    "QueryRunStatus",
    "QueryStreamEvent",
    "PreparedRerankCandidates",
    "ReconcileIssue",
    "ReconcileIssueKind",
    "ReconcileReport",
    "ReconcileService",
    "RecoveredContext",
    "RecoveryAction",
    "RecoveryPlanner",
    "RecoveryRoute",
    "ReciprocalRankFusion",
    "RegisterDocument",
    "RepairRequest",
    "RerankItem",
    "RerankOutcome",
    "RerankingService",
    "RootContext",
    "RetrievalMode",
    "SessionGrant",
    "SearchBranchResult",
    "SearchDiagnostic",
    "SearchMethod",
    "SemanticQueryRunner",
    "ScopeRootService",
    "SparseGoldenSubject",
    "StageTransition",
    "StandardQueryGraph",
    "StandardQueryRequest",
    "StandardQueryResult",
    "VerificationIssue",
    "WorkspaceService",
    "WorkspaceOverview",
    "WorkspaceOverviewService",
    "TraceService",
    "build_persistent_tracing",
    "configure_optional_llm_judge",
    "evaluation_report_dict",
    "evaluate_quality_gate",
    "load_quality_gate_policy",
    "project_query_trace",
    "project_ingestion_trace",
    "write_evaluation_report",
]
