"""Application services that coordinate ports and transactional adapters."""

from enterprise_rag.services.answer_verification import (
    AnswerDraft,
    AnswerOutcome,
    AnswerStatus,
    AnswerVerificationService,
    DraftCitation,
    DraftParagraph,
    RepairRequest,
    VerificationIssue,
)
from enterprise_rag.services.auth import AnonymousSessionService, Principal, SessionGrant
from enterprise_rag.services.cost_guard import (
    BoundedLanguageModel,
    BudgetedQueryRunner,
    CostGuard,
    QueryBudget,
)
from enterprise_rag.services.deep_recovery import (
    DeepRecoveryController,
    DeepRecoveryOutcome,
    DeepRecoveryRequest,
    EvidenceAssessment,
    EvidenceDecision,
    EvidenceItem,
    EvidenceLedger,
    RecoveryAction,
    RecoveryPlanner,
    RecoveryRoute,
    RetrievalMode,
)
from enterprise_rag.services.documents import DocumentRegistrationService, RegisterDocument
from enterprise_rag.services.eval_runner import (
    EvaluationBudgetExceeded,
    EvaluationRunner,
    GoldenFixtureSubject,
    MemoryEvaluationResultCache,
    evaluation_report_dict,
    write_evaluation_report,
)
from enterprise_rag.services.evaluation import DeterministicEvaluator
from enterprise_rag.services.fusion import FusionDiagnostic, FusionResult, ReciprocalRankFusion
from enterprise_rag.services.golden_set import GoldenSetLoader, GoldenSetValidationError
from enterprise_rag.services.health import (
    ComponentHealth,
    ConfigurationHealthProbe,
    HealthProbe,
    HealthReport,
    HealthService,
    HealthStatus,
    PostgreSQLHealthProbe,
)
from enterprise_rag.services.images import EnrichedImage, ImageEnricher, ImageEnrichmentResult
from enterprise_rag.services.ingestion import IngestionPipeline, PipelineRunResult
from enterprise_rag.services.knowledge import (
    KnowledgeApplication,
    KnowledgeQuery,
    McpApplicationService,
)
from enterprise_rag.services.lifecycle import (
    DeletionResult,
    DeletionStep,
    DocumentDeletionService,
    ReconcileIssue,
    ReconcileIssueKind,
    ReconcileReport,
    ReconcileService,
)
from enterprise_rag.services.projection import (
    ProjectionError,
    ProjectionRequest,
    ProjectionResult,
    ProjectionService,
)
from enterprise_rag.services.query_api import (
    QueryApiService,
    QueryCommand,
    QueryExecution,
    QueryProgress,
    QueryProgressStage,
    QueryRunStatus,
    QueryStreamEvent,
)
from enterprise_rag.services.query_planner import PlannerOutcome, QueryPlanningService
from enterprise_rag.services.reranking import RerankingService, RerankItem, RerankOutcome
from enterprise_rag.services.retrieval import (
    DualSearchResult,
    DualSearchService,
    SearchBranchResult,
    SearchDiagnostic,
    SearchMethod,
)
from enterprise_rag.services.scope_root import (
    PreparedRerankCandidates,
    RecoveredContext,
    RootContext,
    ScopeRootService,
)
from enterprise_rag.services.standard_graph import (
    QueryGraphStage,
    QueryGraphStatus,
    StageTransition,
    StandardQueryGraph,
    StandardQueryRequest,
    StandardQueryResult,
)
from enterprise_rag.services.traces import TraceService, build_persistent_tracing
from enterprise_rag.services.workspace import WorkspaceService

__all__ = [
    "AnswerDraft",
    "AnswerOutcome",
    "AnswerStatus",
    "AnswerVerificationService",
    "BoundedLanguageModel",
    "BudgetedQueryRunner",
    "CostGuard",
    "DeletionResult",
    "DeletionStep",
    "DocumentDeletionService",
    "DocumentRegistrationService",
    "EvaluationBudgetExceeded",
    "EvaluationRunner",
    "GoldenSetLoader",
    "GoldenSetValidationError",
    "GoldenFixtureSubject",
    "DeterministicEvaluator",
    "DeepRecoveryController",
    "DeepRecoveryOutcome",
    "DeepRecoveryRequest",
    "DualSearchResult",
    "DualSearchService",
    "DraftCitation",
    "DraftParagraph",
    "EnrichedImage",
    "EvidenceAssessment",
    "EvidenceDecision",
    "EvidenceItem",
    "EvidenceLedger",
    "FusionDiagnostic",
    "FusionResult",
    "ImageEnricher",
    "ImageEnrichmentResult",
    "ComponentHealth",
    "ConfigurationHealthProbe",
    "HealthProbe",
    "HealthReport",
    "HealthService",
    "HealthStatus",
    "IngestionPipeline",
    "KnowledgeApplication",
    "KnowledgeQuery",
    "AnonymousSessionService",
    "PipelineRunResult",
    "PlannerOutcome",
    "McpApplicationService",
    "MemoryEvaluationResultCache",
    "Principal",
    "ProjectionError",
    "ProjectionRequest",
    "ProjectionResult",
    "ProjectionService",
    "PostgreSQLHealthProbe",
    "QueryPlanningService",
    "QueryGraphStage",
    "QueryGraphStatus",
    "QueryApiService",
    "QueryBudget",
    "QueryCommand",
    "QueryExecution",
    "QueryProgress",
    "QueryProgressStage",
    "QueryRunStatus",
    "QueryStreamEvent",
    "PreparedRerankCandidates",
    "ReconcileIssue",
    "ReconcileIssueKind",
    "ReconcileReport",
    "ReconcileService",
    "RecoveredContext",
    "RecoveryAction",
    "RecoveryPlanner",
    "RecoveryRoute",
    "ReciprocalRankFusion",
    "RegisterDocument",
    "RepairRequest",
    "RerankItem",
    "RerankOutcome",
    "RerankingService",
    "RootContext",
    "RetrievalMode",
    "SessionGrant",
    "SearchBranchResult",
    "SearchDiagnostic",
    "SearchMethod",
    "ScopeRootService",
    "StageTransition",
    "StandardQueryGraph",
    "StandardQueryRequest",
    "StandardQueryResult",
    "VerificationIssue",
    "WorkspaceService",
    "TraceService",
    "build_persistent_tracing",
    "evaluation_report_dict",
    "write_evaluation_report",
]
